### ISSUE TITLE
SMTP: Better API for sending mail

### ISSUE THREAD

**Issue by lemol** [qnikst/HaskellNet#33]
Currently we have five different functions to send mails. Some functions names looks confusing to their purposes, so I suggest to have the following two functions:

``` haskell
-- 1
sendMailCustom :: From -> [Destination] -> ByteString -> SMTPConnection -> IO ()
```
- This is a replacement for the actual `sendMail`. It is the most low-level function. Need to specify the sender, the recipients and the just rendered ByteString SMTP mail data.

``` haskell
-- 2
sendMail :: Mail -> SMTPConnection -> IO ()
```
- A possibility to send a just constructed `Mail` data.

And, we may have more high-levels functions with specifics names such as to send plain text mail and to send mime mail or to just construct them:

``` haskell
sendPlainTextMail :: From -> [Destination] -> Subject -> Text -> SMTPConnection -> IO ()
plainTextMail :: From -> [Destination] -> Subject -> Text -> Mail
```
- This aim to be the simplest way to send mail. It may be called `sendSimpleMail`.

``` haskell
sendMimeMail :: From -> [Destination] -> Subject -> [Part] -> SMTPConnection -> IO ()
mimeMail :: From -> [Destination] -> Subject -> [Part] -> Mail
```
- Example:

``` haskell
from = From "Me" "me@mail.com"
tos   = [To "Gato" "gato@...", justEmailTo "agua@...", Cc "Nada" "nada@...", justEmailBcc "bcc@..."]
bsAttachment = InMemoryAttachment "applicaction/octet-stream" "simple.tar.gz" someBS
fileAttachment = FileAttachment "text/js" "/path/to/file.js"
sendMimeMail from tos "Subject" [PlainTextPart "Hello. Bye!", HtmlPart "<html>...", bsAttachment, fileAttachment, ...] conn
```

**Comment by qnikst** [comment]
After thinking a lot on the API I've come to a conclusion that the best route is to deprecate all the methods except for `sendMimeMail2` (but rename it to something more sensible). So the only methods for sending will use `Mail` type from the mime-mail package. For simplicity we can reexport generation methods (or better entire module) from the mime-mail package.

This way there will be the only one package where the work on the email generator API is done and all the helpers are introduced. Otherwise we are reimplementing mime-mail functionality.

What do you think about it?
