### ISSUE TITLE
How to specify sender name via SMPT protocol?

### ISSUE THREAD

**Issue by chshersh** [qnikst/HaskellNet#59]
With the current library interface, it's possible to specify only sender email. However, often, you want to specify a name as well.

Could you, please, tell me how I can specify sender name?

Edit: I'm not sure whether I'm moving in the right direction, but probably here
https://github.com/jtdaugherty/HaskellNet/blob/0e72b70f004bd202db0e45da19379fff03d6f0b7/src/Network/HaskellNet/SMTP.hs#L224
it should be
```
"MAIL FROM: " ++ name ++ " <" ++ param ++ ">"
```

**Comment by qnikst** [comment]
Thanks for the issue and research you've done. The direction seems correct, but everything is a bit more complicated. According to RFC, "MAIL FROM" is the part of the routing and it takes email address in angles w/o user name. In order to set a proper sender name you should fill `From` header and it's done in here:
  https://github.com/qnikst/HaskellNet/blob/0e72b70f004bd202db0e45da19379fff03d6f0b7/src/Network/HaskellNet/SMTP.hs#L315

Currently we always set that to email address.

It moves us in an unfortunate situation as we have only one `String` value that should not have username its part in the `MAIL FROM` and we want username in `From`. However there is a way forward: 

[mime-mail:Address](https://hackage.haskell.org/package/mime-mail-0.5.0/docs/Network-Mail-Mime.html#t:Address) type has everything we need and it has `IsString` instance to it will be almost backward compatible to move to that type.

So I want to propose the following:
  - on this week I'm going to publish a minor version that has build fixes and bugfixes that are not yet on hackage
  - after that I'll start work on the next major release and this issue will be solved.

**Comment by qnikst** [comment]
Before the fix it's possible to use `sendMime2` to set username as in example:

https://github.com/qnikst/HaskellNet/blob/master/example/smtp.hs#L59-L70

**Comment by qnikst** [comment]
PR landed so with a new API you can use `Address` directly and get an expected behaviour
